#ifndef LIBDEMO_PREPROCESSOR_H
#define LIBDEMO_PREPROCESSOR_H


#define PP_RSEQ_N()\
63 ,62 ,61 ,60 ,\
59 ,58 ,57 ,56 ,55 ,54 ,53 ,52 ,51 ,50 ,\
49 ,48 ,47 ,46 ,45 ,44 ,43 ,42 ,41 ,40 ,\
39 ,38 ,37 ,36 ,35 ,34 ,33 ,32 ,31 ,30 ,\
29 ,28 ,27 ,26 ,25 ,24 ,23 ,22 ,21 ,20 ,\
19 ,18 ,17 ,16 ,15 ,14 ,13 ,12 ,11 ,10 ,\
9,8,7,6,5,4,3,2,1,0

#define PP_ARG_N( \
_1  ,_2  ,_3  ,_4  ,_5  ,_6  ,_7  ,_8  ,_9  ,_10 ,\
_11 ,_12 ,_13 ,_14 ,_15 ,_16 ,_17 ,_18 ,_19 ,_20 ,\
_21 ,_22 ,_23 ,_24 ,_25 ,_26 ,_27 ,_28 ,_29 ,_30 ,\
_31 ,_32 ,_33 ,_34 ,_35 ,_36 ,_37 ,_38 ,_39 ,_40 ,\
_41 ,_42 ,_43 ,_44 ,_45 ,_46 ,_47 ,_48 ,_49 ,_50 ,\
_51 ,_52 ,_53 ,_54 ,_55 ,_56 ,_57 ,_58 ,_59 ,_60 ,\
_61 ,_62 ,_63 ,  N , ...) N


#define PP_FW(...) (__VA_ARGS__)
#define PP_NARG_(...) PP_ARG_N PP_FW(__VA_ARGS__)
#define PP_ARGCOUNT(...) PP_NARG_(__VA_ARGS__,PP_RSEQ_N())

#define PP_BUGFX(x) x
#define PP_NARG1(...) PP_BUGFX(PP_ARG_N(__VA_ARGS__))
#define PP_NARG2(...) PP_BUGFX(PP_NARG1(__VA_ARGS__,PP_RSEQ_N()))


#if 1
#define PP_S1(M, v, ...) M(v)
#define PP_S2(M, v, ...) M(v) PP_S1 PP_FW(M, __VA_ARGS__)
#define PP_S3(M, v, ...) M(v) PP_S2 PP_FW(M,__VA_ARGS__)
#define PP_S4(M, v, ...) M(v) PP_S3 PP_FW(M,__VA_ARGS__)
#define PP_S5(M, v, ...) M(v) PP_S4 PP_FW(M,__VA_ARGS__)
#define PP_S6(M, v, ...) M(v) PP_S5 PP_FW(M,__VA_ARGS__)
#define PP_S7(M, v, ...) M(v) PP_S6 PP_FW(M,__VA_ARGS__)
#define PP_S8(M, v, ...) M(v) PP_S7 PP_FW(M,__VA_ARGS__)
#define PP_S9(M, v, ...) M(v) PP_S8 PP_FW(M,__VA_ARGS__)
#define PP_S10(M, v, ...) M(v) PP_S9 PP_FW(M,__VA_ARGS__)
#define PP_S11(M, v, ...) M(v) PP_S10 PP_FW(M,__VA_ARGS__)
#define PP_S12(M, v, ...) M(v) PP_S11 PP_FW(M,__VA_ARGS__)
#define PP_S13(M, v, ...) M(v) PP_S12 PP_FW(M,__VA_ARGS__)
#define PP_S14(M, v, ...) M(v) PP_S13 PP_FW(M,__VA_ARGS__)
#define PP_S15(M, v, ...) M(v) PP_S14 PP_FW(M,__VA_ARGS__)
#define PP_S16(M, v, ...) M(v) PP_S15 PP_FW(M,__VA_ARGS__)
#define PP_S17(M, v, ...) M(v) PP_S16 PP_FW(M,__VA_ARGS__)
#define PP_S18(M, v, ...) M(v) PP_S17 PP_FW(M,__VA_ARGS__)
#define PP_S19(M, v, ...) M(v) PP_S18 PP_FW(M,__VA_ARGS__)
#define PP_S20(M, v, ...) M(v) PP_S19 PP_FW(M,__VA_ARGS__)
#define PP_S21(M, v, ...) M(v) PP_S20 PP_FW(M,__VA_ARGS__)
#define PP_S22(M, v, ...) M(v) PP_S21 PP_FW(M,__VA_ARGS__)
#define PP_S23(M, v, ...) M(v) PP_S22 PP_FW(M,__VA_ARGS__)
#define PP_S24(M, v, ...) M(v) PP_S23 PP_FW(M,__VA_ARGS__)
#define PP_S25(M, v, ...) M(v) PP_S24 PP_FW(M,__VA_ARGS__)
#define PP_S26(M, v, ...) M(v) PP_S25 PP_FW(M,__VA_ARGS__)
#define PP_S27(M, v, ...) M(v) PP_S26 PP_FW(M,__VA_ARGS__)
#define PP_S28(M, v, ...) M(v) PP_S27 PP_FW(M,__VA_ARGS__)
#define PP_S29(M, v, ...) M(v) PP_S28 PP_FW(M,__VA_ARGS__)
#define PP_S30(M, v, ...) M(v) PP_S29 PP_FW(M,__VA_ARGS__)
#define PP_S31(M, v, ...) M(v) PP_S30 PP_FW(M,__VA_ARGS__)
#define PP_S32(M, v, ...) M(v) PP_S31 PP_FW(M,__VA_ARGS__)
#define PP_S33(M, v, ...) M(v) PP_S32 PP_FW(M,__VA_ARGS__)
#define PP_S34(M, v, ...) M(v) PP_S33 PP_FW(M,__VA_ARGS__)
#define PP_S35(M, v, ...) M(v) PP_S34 PP_FW(M,__VA_ARGS__)
#define PP_S36(M, v, ...) M(v) PP_S35 PP_FW(M,__VA_ARGS__)
#define PP_S37(M, v, ...) M(v) PP_S36 PP_FW(M,__VA_ARGS__)
#define PP_S38(M, v, ...) M(v) PP_S37 PP_FW(M,__VA_ARGS__)
#define PP_S39(M, v, ...) M(v) PP_S38 PP_FW(M,__VA_ARGS__)
#define PP_S40(M, v, ...) M(v) PP_S39 PP_FW(M,__VA_ARGS__)
#define PP_S41(M, v, ...) M(v) PP_S40 PP_FW(M,__VA_ARGS__)
#define PP_S42(M, v, ...) M(v) PP_S41 PP_FW(M,__VA_ARGS__)
#define PP_S43(M, v, ...) M(v) PP_S42 PP_FW(M,__VA_ARGS__)
#define PP_S44(M, v, ...) M(v) PP_S43 PP_FW(M,__VA_ARGS__)
#define PP_S45(M, v, ...) M(v) PP_S44 PP_FW(M,__VA_ARGS__)
#define PP_S46(M, v, ...) M(v) PP_S45 PP_FW(M,__VA_ARGS__)
#define PP_S47(M, v, ...) M(v) PP_S46 PP_FW(M,__VA_ARGS__)
#define PP_S48(M, v, ...) M(v) PP_S47 PP_FW(M,__VA_ARGS__)
#define PP_S49(M, v, ...) M(v) PP_S48 PP_FW(M,__VA_ARGS__)
#define PP_S50(M, v, ...) M(v) PP_S49 PP_FW(M,__VA_ARGS__)
#define PP_S51(M, v, ...) M(v) PP_S50 PP_FW(M,__VA_ARGS__)
#define PP_S52(M, v, ...) M(v) PP_S51 PP_FW(M,__VA_ARGS__)
#define PP_S53(M, v, ...) M(v) PP_S52 PP_FW(M,__VA_ARGS__)
#define PP_S54(M, v, ...) M(v) PP_S53 PP_FW(M,__VA_ARGS__)
#define PP_S55(M, v, ...) M(v) PP_S54 PP_FW(M,__VA_ARGS__)
#define PP_S56(M, v, ...) M(v) PP_S55 PP_FW(M,__VA_ARGS__)
#define PP_S57(M, v, ...) M(v) PP_S56 PP_FW(M,__VA_ARGS__)
#define PP_S58(M, v, ...) M(v) PP_S57 PP_FW(M,__VA_ARGS__)
#define PP_S59(M, v, ...) M(v) PP_S58 PP_FW(M,__VA_ARGS__)
#define PP_S60(M, v, ...) M(v) PP_S59 PP_FW(M,__VA_ARGS__)
#define PP_S61(M, v, ...) M(v) PP_S60 PP_FW(M,__VA_ARGS__)
#define PP_S62(M, v, ...) M(v) PP_S61 PP_FW(M,__VA_ARGS__)
#define PP_S63(M, v, ...) M(v) PP_S62 PP_FW(M,__VA_ARGS__)
#define PP_S64(M, v, ...) M(v) PP_S63 PP_FW(M,__VA_ARGS__)

#define PP_SC1(M, v, ...) M(v)
#define PP_SC2(M, v, ...) M(v), PP_SC1 PP_FW(M, __VA_ARGS__)
#define PP_SC3(M, v, ...) M(v), PP_SC2 PP_FW(M,__VA_ARGS__)
#define PP_SC4(M, v, ...) M(v), PP_SC3 PP_FW(M,__VA_ARGS__)
#define PP_SC5(M, v, ...) M(v), PP_SC4 PP_FW(M,__VA_ARGS__)
#define PP_SC6(M, v, ...) M(v), PP_SC5 PP_FW(M,__VA_ARGS__)
#define PP_SC7(M, v, ...) M(v), PP_SC6 PP_FW(M,__VA_ARGS__)
#define PP_SC8(M, v, ...) M(v), PP_SC7 PP_FW(M,__VA_ARGS__)
#define PP_SC9(M, v, ...) M(v), PP_SC8 PP_FW(M,__VA_ARGS__)
#define PP_SC10(M, v, ...) M(v), PP_SC9 PP_FW(M,__VA_ARGS__)
#define PP_SC11(M, v, ...) M(v), PP_SC10 PP_FW(M,__VA_ARGS__)
#define PP_SC12(M, v, ...) M(v), PP_SC11 PP_FW(M,__VA_ARGS__)
#define PP_SC13(M, v, ...) M(v), PP_SC12 PP_FW(M,__VA_ARGS__)
#define PP_SC14(M, v, ...) M(v), PP_SC13 PP_FW(M,__VA_ARGS__)
#define PP_SC15(M, v, ...) M(v), PP_SC14 PP_FW(M,__VA_ARGS__)
#define PP_SC16(M, v, ...) M(v), PP_SC15 PP_FW(M,__VA_ARGS__)
#define PP_SC17(M, v, ...) M(v), PP_SC16 PP_FW(M,__VA_ARGS__)
#define PP_SC18(M, v, ...) M(v), PP_SC17 PP_FW(M,__VA_ARGS__)
#define PP_SC19(M, v, ...) M(v), PP_SC18 PP_FW(M,__VA_ARGS__)
#define PP_SC20(M, v, ...) M(v), PP_SC19 PP_FW(M,__VA_ARGS__)
#define PP_SC21(M, v, ...) M(v), PP_SC20 PP_FW(M,__VA_ARGS__)
#define PP_SC22(M, v, ...) M(v), PP_SC21 PP_FW(M,__VA_ARGS__)
#define PP_SC23(M, v, ...) M(v), PP_SC22 PP_FW(M,__VA_ARGS__)
#define PP_SC24(M, v, ...) M(v), PP_SC23 PP_FW(M,__VA_ARGS__)
#define PP_SC25(M, v, ...) M(v), PP_SC24 PP_FW(M,__VA_ARGS__)
#define PP_SC26(M, v, ...) M(v), PP_SC25 PP_FW(M,__VA_ARGS__)
#define PP_SC27(M, v, ...) M(v), PP_SC26 PP_FW(M,__VA_ARGS__)
#define PP_SC28(M, v, ...) M(v), PP_SC27 PP_FW(M,__VA_ARGS__)
#define PP_SC29(M, v, ...) M(v), PP_SC28 PP_FW(M,__VA_ARGS__)
#define PP_SC30(M, v, ...) M(v), PP_SC29 PP_FW(M,__VA_ARGS__)
#define PP_SC31(M, v, ...) M(v), PP_SC30 PP_FW(M,__VA_ARGS__)
#define PP_SC32(M, v, ...) M(v), PP_SC31 PP_FW(M,__VA_ARGS__)
#define PP_SC33(M, v, ...) M(v), PP_SC32 PP_FW(M,__VA_ARGS__)
#define PP_SC34(M, v, ...) M(v), PP_SC33 PP_FW(M,__VA_ARGS__)
#define PP_SC35(M, v, ...) M(v), PP_SC34 PP_FW(M,__VA_ARGS__)
#define PP_SC36(M, v, ...) M(v), PP_SC35 PP_FW(M,__VA_ARGS__)
#define PP_SC37(M, v, ...) M(v), PP_SC36 PP_FW(M,__VA_ARGS__)
#define PP_SC38(M, v, ...) M(v), PP_SC37 PP_FW(M,__VA_ARGS__)
#define PP_SC39(M, v, ...) M(v), PP_SC38 PP_FW(M,__VA_ARGS__)
#define PP_SC40(M, v, ...) M(v), PP_SC39 PP_FW(M,__VA_ARGS__)
#define PP_SC41(M, v, ...) M(v), PP_SC40 PP_FW(M,__VA_ARGS__)
#define PP_SC42(M, v, ...) M(v), PP_SC41 PP_FW(M,__VA_ARGS__)
#define PP_SC43(M, v, ...) M(v), PP_SC42 PP_FW(M,__VA_ARGS__)
#define PP_SC44(M, v, ...) M(v), PP_SC43 PP_FW(M,__VA_ARGS__)
#define PP_SC45(M, v, ...) M(v), PP_SC44 PP_FW(M,__VA_ARGS__)
#define PP_SC46(M, v, ...) M(v), PP_SC45 PP_FW(M,__VA_ARGS__)
#define PP_SC47(M, v, ...) M(v), PP_SC46 PP_FW(M,__VA_ARGS__)
#define PP_SC48(M, v, ...) M(v), PP_SC47 PP_FW(M,__VA_ARGS__)
#define PP_SC49(M, v, ...) M(v), PP_SC48 PP_FW(M,__VA_ARGS__)
#define PP_SC50(M, v, ...) M(v), PP_SC49 PP_FW(M,__VA_ARGS__)
#define PP_SC51(M, v, ...) M(v), PP_SC50 PP_FW(M,__VA_ARGS__)
#define PP_SC52(M, v, ...) M(v), PP_SC51 PP_FW(M,__VA_ARGS__)
#define PP_SC53(M, v, ...) M(v), PP_SC52 PP_FW(M,__VA_ARGS__)
#define PP_SC54(M, v, ...) M(v), PP_SC53 PP_FW(M,__VA_ARGS__)
#define PP_SC55(M, v, ...) M(v), PP_SC54 PP_FW(M,__VA_ARGS__)
#define PP_SC56(M, v, ...) M(v), PP_SC55 PP_FW(M,__VA_ARGS__)
#define PP_SC57(M, v, ...) M(v), PP_SC56 PP_FW(M,__VA_ARGS__)
#define PP_SC58(M, v, ...) M(v), PP_SC57 PP_FW(M,__VA_ARGS__)
#define PP_SC59(M, v, ...) M(v), PP_SC58 PP_FW(M,__VA_ARGS__)
#define PP_SC60(M, v, ...) M(v), PP_SC59 PP_FW(M,__VA_ARGS__)
#define PP_SC61(M, v, ...) M(v), PP_SC60 PP_FW(M,__VA_ARGS__)
#define PP_SC62(M, v, ...) M(v), PP_SC61 PP_FW(M,__VA_ARGS__)
#define PP_SC63(M, v, ...) M(v), PP_SC62 PP_FW(M,__VA_ARGS__)
#define PP_SC64(M, v, ...) M(v), PP_SC63 PP_FW(M,__VA_ARGS__)

#define PP_GS1(M, v, ...) M v
#define PP_GS2(M, v, ...) M v PP_GS1 PP_FW(M, __VA_ARGS__)
#define PP_GS3(M, v, ...) M v PP_GS2 PP_FW(M,__VA_ARGS__)
#define PP_GS4(M, v, ...) M v PP_GS3 PP_FW(M,__VA_ARGS__)
#define PP_GS5(M, v, ...) M v PP_GS4 PP_FW(M,__VA_ARGS__)
#define PP_GS6(M, v, ...) M v PP_GS5 PP_FW(M,__VA_ARGS__)
#define PP_GS7(M, v, ...) M v PP_GS6 PP_FW(M,__VA_ARGS__)
#define PP_GS8(M, v, ...) M v PP_GS7 PP_FW(M,__VA_ARGS__)
#define PP_GS9(M, v, ...) M v PP_GS8 PP_FW(M,__VA_ARGS__)
#define PP_GS10(M, v, ...) M v PP_GS9 PP_FW(M,__VA_ARGS__)
#define PP_GS11(M, v, ...) M v PP_GS10 PP_FW(M,__VA_ARGS__)
#define PP_GS12(M, v, ...) M v PP_GS11 PP_FW(M,__VA_ARGS__)
#define PP_GS13(M, v, ...) M v PP_GS12 PP_FW(M,__VA_ARGS__)
#define PP_GS14(M, v, ...) M v PP_GS13 PP_FW(M,__VA_ARGS__)
#define PP_GS15(M, v, ...) M v PP_GS14 PP_FW(M,__VA_ARGS__)
#define PP_GS16(M, v, ...) M v PP_GS15 PP_FW(M,__VA_ARGS__)
#define PP_GS17(M, v, ...) M v PP_GS16 PP_FW(M,__VA_ARGS__)
#define PP_GS18(M, v, ...) M v PP_GS17 PP_FW(M,__VA_ARGS__)
#define PP_GS19(M, v, ...) M v PP_GS18 PP_FW(M,__VA_ARGS__)
#define PP_GS20(M, v, ...) M v PP_GS19 PP_FW(M,__VA_ARGS__)
#define PP_GS21(M, v, ...) M v PP_GS20 PP_FW(M,__VA_ARGS__)
#define PP_GS22(M, v, ...) M v PP_GS21 PP_FW(M,__VA_ARGS__)
#define PP_GS23(M, v, ...) M v PP_GS22 PP_FW(M,__VA_ARGS__)
#define PP_GS24(M, v, ...) M v PP_GS23 PP_FW(M,__VA_ARGS__)
#define PP_GS25(M, v, ...) M v PP_GS24 PP_FW(M,__VA_ARGS__)
#define PP_GS26(M, v, ...) M v PP_GS25 PP_FW(M,__VA_ARGS__)
#define PP_GS27(M, v, ...) M v PP_GS26 PP_FW(M,__VA_ARGS__)
#define PP_GS28(M, v, ...) M v PP_GS27 PP_FW(M,__VA_ARGS__)
#define PP_GS29(M, v, ...) M v PP_GS28 PP_FW(M,__VA_ARGS__)
#define PP_GS30(M, v, ...) M v PP_GS29 PP_FW(M,__VA_ARGS__)
#define PP_GS31(M, v, ...) M v PP_GS30 PP_FW(M,__VA_ARGS__)
#define PP_GS32(M, v, ...) M v PP_GS31 PP_FW(M,__VA_ARGS__)
#define PP_GS33(M, v, ...) M v PP_GS32 PP_FW(M,__VA_ARGS__)
#define PP_GS34(M, v, ...) M v PP_GS33 PP_FW(M,__VA_ARGS__)
#define PP_GS35(M, v, ...) M v PP_GS34 PP_FW(M,__VA_ARGS__)
#define PP_GS36(M, v, ...) M v PP_GS35 PP_FW(M,__VA_ARGS__)
#define PP_GS37(M, v, ...) M v PP_GS36 PP_FW(M,__VA_ARGS__)
#define PP_GS38(M, v, ...) M v PP_GS37 PP_FW(M,__VA_ARGS__)
#define PP_GS39(M, v, ...) M v PP_GS38 PP_FW(M,__VA_ARGS__)
#define PP_GS40(M, v, ...) M v PP_GS39 PP_FW(M,__VA_ARGS__)
#define PP_GS41(M, v, ...) M v PP_GS40 PP_FW(M,__VA_ARGS__)
#define PP_GS42(M, v, ...) M v PP_GS41 PP_FW(M,__VA_ARGS__)
#define PP_GS43(M, v, ...) M v PP_GS42 PP_FW(M,__VA_ARGS__)
#define PP_GS44(M, v, ...) M v PP_GS43 PP_FW(M,__VA_ARGS__)
#define PP_GS45(M, v, ...) M v PP_GS44 PP_FW(M,__VA_ARGS__)
#define PP_GS46(M, v, ...) M v PP_GS45 PP_FW(M,__VA_ARGS__)
#define PP_GS47(M, v, ...) M v PP_GS46 PP_FW(M,__VA_ARGS__)
#define PP_GS48(M, v, ...) M v PP_GS47 PP_FW(M,__VA_ARGS__)
#define PP_GS49(M, v, ...) M v PP_GS48 PP_FW(M,__VA_ARGS__)
#define PP_GS50(M, v, ...) M v PP_GS49 PP_FW(M,__VA_ARGS__)
#define PP_GS51(M, v, ...) M v PP_GS50 PP_FW(M,__VA_ARGS__)
#define PP_GS52(M, v, ...) M v PP_GS51 PP_FW(M,__VA_ARGS__)
#define PP_GS53(M, v, ...) M v PP_GS52 PP_FW(M,__VA_ARGS__)
#define PP_GS54(M, v, ...) M v PP_GS53 PP_FW(M,__VA_ARGS__)
#define PP_GS55(M, v, ...) M v PP_GS54 PP_FW(M,__VA_ARGS__)
#define PP_GS56(M, v, ...) M v PP_GS55 PP_FW(M,__VA_ARGS__)
#define PP_GS57(M, v, ...) M v PP_GS56 PP_FW(M,__VA_ARGS__)
#define PP_GS58(M, v, ...) M v PP_GS57 PP_FW(M,__VA_ARGS__)
#define PP_GS59(M, v, ...) M v PP_GS58 PP_FW(M,__VA_ARGS__)
#define PP_GS60(M, v, ...) M v PP_GS59 PP_FW(M,__VA_ARGS__)
#define PP_GS61(M, v, ...) M v PP_GS60 PP_FW(M,__VA_ARGS__)
#define PP_GS62(M, v, ...) M v PP_GS61 PP_FW(M,__VA_ARGS__)
#define PP_GS63(M, v, ...) M v PP_GS62 PP_FW(M,__VA_ARGS__)
#define PP_GS64(M, v, ...) M v PP_GS63 PP_FW(M,__VA_ARGS__)

#define PP_GSC1(M, v, ...) M v
#define PP_GSC2(M, v, ...) M v, PP_GSC1 PP_FW(M, __VA_ARGS__)
#define PP_GSC3(M, v, ...) M v, PP_GSC2 PP_FW(M,__VA_ARGS__)
#define PP_GSC4(M, v, ...) M v, PP_GSC3 PP_FW(M,__VA_ARGS__)
#define PP_GSC5(M, v, ...) M v, PP_GSC4 PP_FW(M,__VA_ARGS__)
#define PP_GSC6(M, v, ...) M v, PP_GSC5 PP_FW(M,__VA_ARGS__)
#define PP_GSC7(M, v, ...) M v, PP_GSC6 PP_FW(M,__VA_ARGS__)
#define PP_GSC8(M, v, ...) M v, PP_GSC7 PP_FW(M,__VA_ARGS__)
#define PP_GSC9(M, v, ...) M v, PP_GSC8 PP_FW(M,__VA_ARGS__)
#define PP_GSC10(M, v, ...) M v, PP_GSC9 PP_FW(M,__VA_ARGS__)
#define PP_GSC11(M, v, ...) M v, PP_GSC10 PP_FW(M,__VA_ARGS__)
#define PP_GSC12(M, v, ...) M v, PP_GSC11 PP_FW(M,__VA_ARGS__)
#define PP_GSC13(M, v, ...) M v, PP_GSC12 PP_FW(M,__VA_ARGS__)
#define PP_GSC14(M, v, ...) M v, PP_GSC13 PP_FW(M,__VA_ARGS__)
#define PP_GSC15(M, v, ...) M v, PP_GSC14 PP_FW(M,__VA_ARGS__)
#define PP_GSC16(M, v, ...) M v, PP_GSC15 PP_FW(M,__VA_ARGS__)
#define PP_GSC17(M, v, ...) M v, PP_GSC16 PP_FW(M,__VA_ARGS__)
#define PP_GSC18(M, v, ...) M v, PP_GSC17 PP_FW(M,__VA_ARGS__)
#define PP_GSC19(M, v, ...) M v, PP_GSC18 PP_FW(M,__VA_ARGS__)
#define PP_GSC20(M, v, ...) M v, PP_GSC19 PP_FW(M,__VA_ARGS__)
#define PP_GSC21(M, v, ...) M v, PP_GSC20 PP_FW(M,__VA_ARGS__)
#define PP_GSC22(M, v, ...) M v, PP_GSC21 PP_FW(M,__VA_ARGS__)
#define PP_GSC23(M, v, ...) M v, PP_GSC22 PP_FW(M,__VA_ARGS__)
#define PP_GSC24(M, v, ...) M v, PP_GSC23 PP_FW(M,__VA_ARGS__)
#define PP_GSC25(M, v, ...) M v, PP_GSC24 PP_FW(M,__VA_ARGS__)
#define PP_GSC26(M, v, ...) M v, PP_GSC25 PP_FW(M,__VA_ARGS__)
#define PP_GSC27(M, v, ...) M v, PP_GSC26 PP_FW(M,__VA_ARGS__)
#define PP_GSC28(M, v, ...) M v, PP_GSC27 PP_FW(M,__VA_ARGS__)
#define PP_GSC29(M, v, ...) M v, PP_GSC28 PP_FW(M,__VA_ARGS__)
#define PP_GSC30(M, v, ...) M v, PP_GSC29 PP_FW(M,__VA_ARGS__)
#define PP_GSC31(M, v, ...) M v, PP_GSC30 PP_FW(M,__VA_ARGS__)
#define PP_GSC32(M, v, ...) M v, PP_GSC31 PP_FW(M,__VA_ARGS__)
#define PP_GSC33(M, v, ...) M v, PP_GSC32 PP_FW(M,__VA_ARGS__)
#define PP_GSC34(M, v, ...) M v, PP_GSC33 PP_FW(M,__VA_ARGS__)
#define PP_GSC35(M, v, ...) M v, PP_GSC34 PP_FW(M,__VA_ARGS__)
#define PP_GSC36(M, v, ...) M v, PP_GSC35 PP_FW(M,__VA_ARGS__)
#define PP_GSC37(M, v, ...) M v, PP_GSC36 PP_FW(M,__VA_ARGS__)
#define PP_GSC38(M, v, ...) M v, PP_GSC37 PP_FW(M,__VA_ARGS__)
#define PP_GSC39(M, v, ...) M v, PP_GSC38 PP_FW(M,__VA_ARGS__)
#define PP_GSC40(M, v, ...) M v, PP_GSC39 PP_FW(M,__VA_ARGS__)
#define PP_GSC41(M, v, ...) M v, PP_GSC40 PP_FW(M,__VA_ARGS__)
#define PP_GSC42(M, v, ...) M v, PP_GSC41 PP_FW(M,__VA_ARGS__)
#define PP_GSC43(M, v, ...) M v, PP_GSC42 PP_FW(M,__VA_ARGS__)
#define PP_GSC44(M, v, ...) M v, PP_GSC43 PP_FW(M,__VA_ARGS__)
#define PP_GSC45(M, v, ...) M v, PP_GSC44 PP_FW(M,__VA_ARGS__)
#define PP_GSC46(M, v, ...) M v, PP_GSC45 PP_FW(M,__VA_ARGS__)
#define PP_GSC47(M, v, ...) M v, PP_GSC46 PP_FW(M,__VA_ARGS__)
#define PP_GSC48(M, v, ...) M v, PP_GSC47 PP_FW(M,__VA_ARGS__)
#define PP_GSC49(M, v, ...) M v, PP_GSC48 PP_FW(M,__VA_ARGS__)
#define PP_GSC50(M, v, ...) M v, PP_GSC49 PP_FW(M,__VA_ARGS__)
#define PP_GSC51(M, v, ...) M v, PP_GSC50 PP_FW(M,__VA_ARGS__)
#define PP_GSC52(M, v, ...) M v, PP_GSC51 PP_FW(M,__VA_ARGS__)
#define PP_GSC53(M, v, ...) M v, PP_GSC52 PP_FW(M,__VA_ARGS__)
#define PP_GSC54(M, v, ...) M v, PP_GSC53 PP_FW(M,__VA_ARGS__)
#define PP_GSC55(M, v, ...) M v, PP_GSC54 PP_FW(M,__VA_ARGS__)
#define PP_GSC56(M, v, ...) M v, PP_GSC55 PP_FW(M,__VA_ARGS__)
#define PP_GSC57(M, v, ...) M v, PP_GSC56 PP_FW(M,__VA_ARGS__)
#define PP_GSC58(M, v, ...) M v, PP_GSC57 PP_FW(M,__VA_ARGS__)
#define PP_GSC59(M, v, ...) M v, PP_GSC58 PP_FW(M,__VA_ARGS__)
#define PP_GSC60(M, v, ...) M v, PP_GSC59 PP_FW(M,__VA_ARGS__)
#define PP_GSC61(M, v, ...) M v, PP_GSC60 PP_FW(M,__VA_ARGS__)
#define PP_GSC62(M, v, ...) M v, PP_GSC61 PP_FW(M,__VA_ARGS__)
#define PP_GSC63(M, v, ...) M v, PP_GSC62 PP_FW(M,__VA_ARGS__)
#define PP_GSC64(M, v, ...) M v, PP_GSC63 PP_FW(M,__VA_ARGS__)


#define PP_BASE_CONCAT(a, ...) a ## __VA_ARGS__
#define PP_CONCAT(a, ...) PP_BASE_CONCAT(a, __VA_ARGS__)
#define PP_PREFIX(Method) PP_CONCAT(PP_, Method)
#define PP_SUFFIX(N) N
#define PP_ENTRY(Method,N) PP_CONCAT(PP_PREFIX(Method), PP_SUFFIX(N))



#define EVAL(...)  EVAL1(EVAL1(EVAL1(__VA_ARGS__)))
#define EVAL1(...) EVAL2(EVAL2(EVAL2(__VA_ARGS__)))
#define EVAL2(...) EVAL3(EVAL3(EVAL3(__VA_ARGS__)))
#define EVAL3(...) EVAL4(EVAL4(EVAL4(__VA_ARGS__)))
#define EVAL4(...) EVAL5(EVAL5(EVAL5(__VA_ARGS__)))
#define EVAL5(...) __VA_ARGS__


#define PP_CALL_PP_SN( Method, Func, N, ...) PP_CALL_PP_SN_( Method, Func, N, __VA_ARGS__)
#define PP_CALL_PP_SN_( Method, Func, N, ...) PP_ENTRY(Method,N) PP_FW(Func, __VA_ARGS__) 
 
#define PP_FOREACH(Func, ...) PP_CALL_PP_SN( S, Func, PP_ARGCOUNT PP_FW(__VA_ARGS__), __VA_ARGS__ )
#define PP_FOREACH_ASLIST(Func, ...) PP_CALL_PP_SN( SC, Func, PP_ARGCOUNT PP_FW(__VA_ARGS__), __VA_ARGS__ )
#define PP_FOREACH_GROUP(Func, ...) EVAL(PP_CALL_PP_SN( GS, Func, PP_ARGCOUNT PP_FW(__VA_ARGS__), __VA_ARGS__ ))
//#define PP_FOREACH_GROUP(Func, ...) PP_CALL_PP_SN( GS, Func, PP_ARGCOUNT PP_FW(__VA_ARGS__), __VA_ARGS__ )
//#define PP_FOREACH_GROUP(Func, ...) PP_CALL_PP_SN( GS, Func, PP_BUGFX(PP_NARG2(__VA_ARGS__))) (__VA_ARGS__ )
#define PP_FOREACH_GROUP_ASLIST(Func, ...) PP_CALL_PP_SN( GSC, Func, PP_ARGCOUNT PP_FW(__VA_ARGS__), __VA_ARGS__ )
#else

#define PP_BUGFX(x) x

#define PP_NARG2(...) PP_BUGFX(PP_NARG1(__VA_ARGS__,PP_RSEQ_N()))
#define PP_NARG1(...) PP_BUGFX(PP_ARG_N(__VA_ARGS__))


#define PP_GS2(M, v) M v
#define PP_GS1(M, v) PP_GS2(M, v)
#define PP_FOREACH_GROUP(Func,...) PP_GS1(Func,PP_BUGFX(PP_NARG2(__VA_ARGS__))) (__VA_ARGS__)

#endif


//________________

#endif
